### PR TITLE
Import branch Fsword73 kernel1

### PR DESCRIPTION
**Pull request by merceyz**
This PR imports the changes done by @fsword73 from the branch `fsword73-kernel1` into `master`

Quick summary of the changes in this PR:
- BackpropWeightsAuto, BackwardAuto, and ForwardAuto now uses microseconds
- Fixed memory leak in BackpropWeightsAuto, BackwardAuto, and ForwardAuto
- Added new kernels BackpropWeightsFsword73 and BackpropWeightsFsword73_BatchSize

Discussion and more details can be found in #66

### CODE REVIEW

**Comment by hughperkins** [comment]
Awesome! :) . Experimentally, I've granted you 'push' access to the DeepCL repo.  So, once you are happy that everything looks good, please go ahead and merge the PR.

**Comment by merceyz** [comment]
Thank you :)
I would like to rewrite the *Auto classes, would that be ok?

**Comment by hughperkins** [comment]
> I would like to rewrite the *Auto classes, would that be ok?

Sounds good to me :) . Just out of personal curiosity, what changes are you thinking of doing?

**Comment by merceyz** [comment]
The code is a little bit messy, can be done without the arrays, also it keeps kernels in memory that isn't used. So I thought i'd change that

**Comment by hughperkins** [comment]
Cool, sounds good :)

**Pull request merged**
